// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH__SjCBJBLj0j6bZBpnZLI2sJgmstycE',
    appId: '1:373552463340:android:8ffd40014fd8726c50d4c9',
    messagingSenderId: '373552463340',
    projectId: 'student-planner-9cb62',
    databaseURL: 'https://student-planner-9cb62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-planner-9cb62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LowKKHXEBQA6dQ_IGG9Zo299wTWmQkE',
    appId: '1:373552463340:ios:09b6500835e57d6750d4c9',
    messagingSenderId: '373552463340',
    projectId: 'student-planner-9cb62',
    databaseURL: 'https://student-planner-9cb62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'student-planner-9cb62.firebasestorage.app',
    iosBundleId: 'com.vanalvan.studentPlanner',
  );
}
